// Embeds sql/*.sql into src/generated/sql.ts as string constants.
// The .sql files are the single source of truth; run via `npm run embed-sql`
// (wired into prebuild/pretest).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const files = [
  ['TABLES_SQL', 'tables.sql'],
  ['FUNCTIONS_SQL', 'functions.sql'],
];

let out = '// AUTO-GENERATED by scripts/embed-sql.mjs from sql/*.sql — do not edit.\n';
for (const [name, file] of files) {
  const sql = readFileSync(join(root, 'sql', file), 'utf8');
  if (!/\{\{ns\}\}/.test(sql)) {
    throw new Error(`${file}: expected {{ns}} namespace placeholders`);
  }
  out += `\nexport const ${name} = ${JSON.stringify(sql)};\n`;
}

mkdirSync(join(root, 'src', 'generated'), { recursive: true });
writeFileSync(join(root, 'src', 'generated', 'sql.ts'), out);
console.log('Generated src/generated/sql.ts');
